import { useEffect, useState } from 'react'
import Head from 'next/head'
import List from '../components/list/list'
import Form from '../components/form/form'
import Container from '../components/container/container'

export default function Home() {
	const [items, setItems] = useState([])

	useEffect(() => {
		fetch('/api/progress')
			.then((res) => res.json())
			.then((data) => setItems(data.result))
	}, [])

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container>
				<Form items={items} setItems={setItems} />
				<List items={items} setItems={setItems} />
			</Container>
		</div>
	)
}
